### ISSUE TITLE
The Bot has hidden chars

### ISSUE THREAD

**Issue by UjjwalD77** [Simple2006/DankMemerCoinFarmer#2]
If you catch a dragon ... the Bot has hidden chars in the text to type....
and the script isn't able to find the text to type because of it...
Is there a way around it?

**Comment by iminthis** [comment]
> If you catch a dragon ... the Bot has hidden chars in the text to type....
> and the script isn't able to find the text to type because of it...
> Is there a way around it?

How do you know there are hidden characters? I wasn't able to find any.

If you are referring to the code block text around it, that shouldn't be an issue. To confirm this, I just tested and confirmed that the code blocks are not the cause of the issue. I also briefly tried to send a few dragon messages myself and react to them and they did work.

I just added some more dragon spawn reactions so maybe check if it works for you now. It could have just been that the reactions weren't updated yet. 

Sorry if this didn't help you... If you could provide some sort of example if possible, I could take a look!
