### ISSUE TITLE
problem with dankmemersend.py

### ISSUE THREAD

**Issue by saathvikS** [Simple2006/DankMemerCoinFarmer#3]
I am getting an issue when I try to run dankmemersend.py. I have copied the issue below. Please let me know how to fix this @Simple2006.

Traceback (most recent call last):
  File "dankmemersend.py", line 28, in <module>
    client.run(token, bot = False)
    
AttributeError: 'NoneType' object has no attribute 'strip'

  Thanks!

**Comment by iminthis** [comment]
@saathvikS I have changed the code in the file. Re download it from the repository. Make sure to put your token where it says, "ENTER TOKEN"

**Comment by saathvikS** [comment]
Thank you so much!!! It works now!
