### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Shizuka-minamoto** [Simple2006/DankMemerCoinFarmer#4]
can we host it on heroku?

**Comment by iminthis** [comment]
Yes, I personally hosted it on heroku.

Make sure you have your environment variables named correctly on heroku and set it to run `main.py` and you should be fine!

Sorry if there are other complications, I recently modified the code to be used for me personally.

**Comment by Shizuka-minamoto** [comment]
its showing error on hosting it to heroku
can you assist me on discord in hosting it to heroku?

**Comment by iminthis** [comment]
can you show me the error?

**Comment by Shizuka-minamoto** [comment]
[typer837857854-logs-1616389397167.txt](https://github.com/Simple2006/DankMemerCoinFarmer/files/6179566/typer837857854-logs-1616389397167.txt)
here is the error logs

**Comment by iminthis** [comment]
Did you not add your token in the heroku environment variables?

**Comment by Shizuka-minamoto** [comment]
oops my bad, i have added the token in dankmemerReact.py and dankmemerSend.py 
i removed the token from here and added it in heroku env,its working fine now
Thanks for your time!

**Comment by Shizuka-minamoto** [comment]
i have 2 more questuons :
1. is it possible to let the script work for 22 hours and then sleep for next 2 hours?
2. is it possible to make it in a way that it take parts in events in 2-3 channels instead of 1?
sorry for disturbing you again...

**Comment by iminthis** [comment]
Yes, it is. You will have to code that on your own though

**Comment by Shizuka-minamoto** [comment]
thanks!
keep up the great work!
